spring:
  application:
    name: rag

  docker:
    compose:
      enabled: false

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: gemma3:4b
      embedding:
        model: nomic-embed-text

    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 768

  datasource:
    url: jdbc:postgresql://localhost:5433/ragdb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080
